### ISSUE TITLE
Issue with numpy.array(input, ndim=2)

### ISSUE THREAD

**Issue by CStrue** [makeyourownneuralnetwork/makeyourownneuralnetwork#23]
Hi, first of all I want to mention this is a great book and good reading.

Though when running the code I run into some trouble.
I set up a docker ubuntu image, so I'm not running the code with the notebook but manually from console. It seems that there is a problem with numpy's array class. I doesn't matter whether i run it with python3 or python 2.7 --> same issue

When running the code i get the following issue (numpy 1.13). Could you give any hint how to solve this?

`python3 neuralNetwork.py
Traceback (most recent call last):
  File "neuralNetwork.py", line 141, in <module>
    main()
  File "neuralNetwork.py", line 105, in main
    n.train(inputs, targets)
  File "neuralNetwork.py", line 38, in train
    inputs = numpy.array(inputs_list, ndim=2).T
TypeError: 'ndim' is an invalid keyword argument for this function`

Source code attached as txt file, since it breaks formatting.

**Comment by CStrue** [comment]
[neuralNetwork.txt](https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/files/1275494/neuralNetwork.txt)

**Comment by CStrue** [comment]
found it - there was a typo in my code.
